[profile.default]
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@hyperlane-xyz/=lib/hyperlane-monorepo/solidity/contracts/",
    "forge-std/=lib/forge-std/src/"
]
test = "test"
cache_path = "cache_forge"
optimizer = true
optimizer_runs = 10000
solc_version = "0.8.19"
build_info = true
extra_output = ["storageLayout"]
auto_detect_remappings = false
fs_permissions = [{ access = "read", path = "./" }]

[profile.ci]
fuzz_runs = 10_000
verbosity = 3

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
